#!/bin/bash

# Usage:
# ./CreateDoxygen

# 1.- Goes to the folder
cd ..

# 2.- Copy src/
cp -f *.cpp doc
cp -f -R Strategies/*.cpp doc
cp -f -R Tree/*.cpp doc

# 3.- Copy include/
cp -f *.hpp doc
cp -f -R Strategies/*.hpp doc
cp -f -R Tree/*hpp doc

# 4.- return to main folder
cd doc

# 5.- Execute doxygen
doxygen

# 6.- Clean info
rm -f -R ./*.cpp ./*.h ./*.hpp

# 7.- Open with Firefox
firefox html/index.html

